build:
- [bash, ./_esy/build, "#{ocaml.lib / 'ocaml'}"]
exportedEnv:
  OCAMLLIB:
    val: "#{@opam/ocamlfind.install / 'lib' / 'ocaml'}"
    scope: global
  CAML_LD_LIBRARY_PATH:
    val: "#{@opam/ocamlfind.install / 'lib' / 'ocaml' / 'stublibs' : @opam/ocamlfind.install / 'lib' / 'ocaml' : $CAML_LD_LIBRARY_PATH}"
    scope: global
  OCAML_TOPLEVEL_PATH:
    val: "#{@opam/ocamlfind.install / 'lib' / 'ocaml'}"
    scope: global
opam:
  url: "http://download2.camlcity.org/download/findlib-1.7.3.tar.gz"
  checksum: "0c3f052b02e9249f3bc9fe3ad6f69de0"
  files:
  - name: _esy/build
    content: |
      #!/bin/bash

      set -euo pipefail
      set -x

      #
      # Shim OCAMLLIB so that we can write topfind there
      #

      REAL_OCAMLLIB="$1"

      mkdir -p $cur__install/lib/ocaml
      cd $cur__install/lib/ocaml

      for filename in `ls -1 $REAL_OCAMLLIB`; do
        ln -s $REAL_OCAMLLIB/$filename $filename;
      done

      #
      # Build
      #

      cd $cur__root

      export OCAMLLIB="$cur__install/lib/ocaml"

      ./configure \
        -bindir $cur__install/bin \
        -sitelib $cur__install/lib \
        -mandir $cur__install/man \
        -config $cur__install/lib/findlib.conf \
        -no-custom \
        -no-camlp4

      make all
      make opt
      make install

      (opam-installer --prefix=$cur__install || true)
