build:
- make
install:
- [make, install]
opam:
  patches:
  - name: fix-install.patch
    content: |
      diff --git a/src/META b/src/META
      index 66ac170..9c04517 100644
      --- a/src/META
      +++ b/src/META
      @@ -1,13 +1,11 @@
       # This META is the one provided by findlib when the "num" library was
      -# part of the core OCaml distribution.  For backward compatibility,
      -# it installs into OCaml's standard library directory, not in a subdirectory
      +# part of the core OCaml distribution.
       
       requires = "num.core"
       requires(toploop) = "num.core,num-top"
       version = "1.0"
       description = "Arbitrary-precision rational arithmetic"
       package "core" (
      -  directory = "^"
         version = "1.0"
         browse_interfaces = ""
         archive(byte) = "nums.cma"
      diff --git a/src/Makefile b/src/Makefile
      index 46179ae..42654fb 100644
      --- a/src/Makefile
      +++ b/src/Makefile
      @@ -84,18 +84,13 @@ endif
       TOINSTALL_STUBS=dllnums$(EXT_DLL)
       
       install:
      -	$(OCAMLFIND) install num META
      -	$(INSTALL_DATA) $(TOINSTALL) $(STDLIBDIR)
       ifeq "$(SUPPORTS_SHARED_LIBRARIES)" "true"
      -	$(INSTALL_DIR) $(STDLIBDIR)/stublibs
      -	$(INSTALL_DLL) $(TOINSTALL_STUBS) $(STDLIBDIR)/stublibs
      +	$(OCAMLFIND) install num META $(TOINSTALL) $(TOINSTALL_STUBS)
      +else
      +	$(OCAMLFIND) install num META $(TOINSTALL)
       endif
       
       uninstall:
      -	cd $(STDLIBDIR) && rm -f $(TOINSTALL)
      -ifeq "$(SUPPORTS_SHARED_LIBRARIES)" "true"
      -	cd $(STDLIBDIR)/stublibs && rm -f $(TOINSTALL_STUBS) 
      -endif
        $(OCAMLFIND) remove num
       
       clean:
