build:
- make
install:
- [make, install]
opam:
  patches:
  - name: fix-install.patch
    content: |
      diff --git a/src/Makefile b/src/Makefile
      index 97dc074..daf98a2 100644
      --- a/src/Makefile
      +++ b/src/Makefile
      @@ -84,9 +84,9 @@ TOINSTALL_STUBS=dllnums.$(SO)
       
       install:
       	$(OCAMLFIND) install num META
      -	$(INSTALL_DATA) $(TOINSTALL) $(STDLIBDIR)
      +	$(INSTALL_DATA) $(TOINSTALL) $(OCAMLFIND_DESTDIR)/num
       ifeq "$(SUPPORTS_SHARED_LIBRARIES)" "true"
      -	$(INSTALL_DLL) $(TOINSTALL_STUBS) $(STDLIBDIR)/stublibs
      +	$(INSTALL_DLL) $(TOINSTALL_STUBS) $(OCAMLFIND_DESTDIR)/stublibs
       endif
       
       uninstall:
       

