build:
- make
install:
- [make, install]
opam:
  patches:
  - name: fix-meta.patch
    content: |
      diff --git a/src/META b/src/META
      index 66ac170..fbe8d00 100644
      --- a/src/META
      +++ b/src/META
      @@ -7,7 +7,6 @@ requires(toploop) = "num.core,num-top"
       version = "1.0"
       description = "Arbitrary-precision rational arithmetic"
       package "core" (
      -  directory = "^"
         version = "1.0"
         browse_interfaces = ""
         archive(byte) = "nums.cma"
  - name: fix-install.patch
    content: |
      diff --git a/src/Makefile b/src/Makefile
      index 97dc074..4acb96f 100644
      --- a/src/Makefile
      +++ b/src/Makefile
      @@ -83,17 +83,13 @@ endif
       TOINSTALL_STUBS=dllnums.$(SO)
       
       install:
      -	$(OCAMLFIND) install num META
      -	$(INSTALL_DATA) $(TOINSTALL) $(STDLIBDIR)
       ifeq "$(SUPPORTS_SHARED_LIBRARIES)" "true"
      -	$(INSTALL_DLL) $(TOINSTALL_STUBS) $(STDLIBDIR)/stublibs
      +	$(OCAMLFIND) install num META $(TOINSTALL) $(TOINSTALL_STUBS)
      +else
      +	$(OCAMLFIND) install num META $(TOINSTALL)
       endif
       
       uninstall:
      -	cd $(STDLIBDIR) && rm -f $(TOINSTALL)
      -ifeq "$(SUPPORTS_SHARED_LIBRARIES)" "true"
      -	cd $(STDLIBDIR)/stublibs && rm -f $(TOINSTALL_STUBS) 
      -endif
       	$(OCAMLFIND) remove num
       
       clean:
