build:
- 'true'
peerDependencies:
  # ocamlbuild was distributed with OCaml < 4.03 but we can't use any of the
  # released ocamlbuild versions b/c of a bug
  # https://github.com/ocaml/ocamlbuild/issues/69 which is fixed but not released
  # on opam.
  #
  # Because of that we put this restriction and ask users who want to use OCaml
  # >=4.03 to pin ocamlbuild to esy-ocaml/ocamlbuild#0.11.0-esy
  ocaml: <4.3.0
